source.scss = "modules/sectionnav"
source.js = "modules/sectionnav"
source.images = "examples/images"
output.base = "target/sectionnav-example"
output.js = "target/sectionnav-example/js"
output.css = "target/sectionnav-example/css"
output.images = "target/sectionnav-example/images"
manifest = "target/sectionnav-example/manifest.json"
minify = true
source-maps = false
jam.enabled = false
